name: Github Actions Demo
on: [push]
jobs:
  sample-job:
    runs-on: ubuntu:latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test
        run: |
          echo "Hello Github actions"
          which docker
